// Run-time:
//   env-var: YKD_SERIALISE_COMPILATION=1
//   env-var: YKD_PRINT_JITSTATE=1
//   env-var: YKD_PRINT_IR=aot,jit-post-opt
//   stderr:
//     jit-state: start-tracing
//     y=201
//     jit-state: stop-tracing
//     ...
//     --- Begin aot ---
//     ...
//     @{{fname1}} = constant [7 x i8] c"inner1\00"
//     @{{fname2}} = constant [7 x i8] c"inner2\00"
//     ...
//     define dso_local {{size_t}} @inner1({{size_t}} noundef %0, {{size_t}} noundef %1, {{size_t}} noundef %2)...
//       ...
//     }
//     ...
//     define dso_local {{size_t}} @inner2({{size_t}} noundef %0, {{size_t}} noundef %1, {{size_t}} noundef %2)...
//       ...
//     }
//     ...
//     define dso_local i32 @main(...
//       ...
//       call void (ptr, i64, ...) @__yk_record_promote_usize(ptr @{{fname1}}, {{size_t}} 2, {{size_t}} 0, {{size_t}} %{{x1}}, {{size_t}} 2, {{size_t}} %{{z1}})...
//       call void (i64, i32, ...) @llvm.experimental.stackmap(...
//       %{{y2}} = call {{size_t}} @inner1({{size_t}} noundef %{{x1}}, {{size_t}} noundef %{{y1}}, {{size_t}} noundef %{{z1}})...
//       ...
//       call void (ptr, i64, ...) @__yk_record_promote_usize(ptr @{{fname2}}, {{size_t}} 2, {{size_t}} 0, {{size_t}} %{{x2}}, {{size_t}} 2, {{size_t}} %{{z2}})...
//       call void (i64, i32, ...) @llvm.experimental.stackmap(...
//       %{{y4}} = call {{size_t}} @inner2({{size_t}} noundef %{{x2}}, {{size_t}} noundef %{{y3}}, {{size_t}} noundef %{{z2}})...
//       ...
//     }
//     ...
//     --- End aot ---
//     --- Begin jit-post-opt ---
//     ...
//     define ptr @__yk_compiled_trace_0(...
//       ...
//       %{{condx1}} = icmp eq i64 {{jitx1}}, 111
//       br i1 %{{condx1}}, label %{{succbbx1}}, label %{{failbbx1}}
//
//     {{succbbx1}}:...
//       ...
//       br label %{{succbbx1cont}}
//
//     {{failbbx1}}:...
//       ...
//       %{{deoptx1}} = call ptr (...) @llvm.experimental.deoptimize...
//       ret ...
//
//     {{succbbx1cont}}:...
//       ...
//       %{{condz1}} = icmp eq i64 {{jitz1}}, 89
//       br i1 %{{condz1}}, label %{{succbbz1}}, label %{{failbbz1}}
//
//     {{failbbz1}}:...
//       ...
//       %{{deoptz1}} = call ptr (...) @llvm.experimental.deoptimize...
//       ret ...
//
//     {{succbbz1}}:...
//       ...
//       %{{res1}} = add {{size_t}} %{{arg1}}, 200...
//       ...
//       %{{condx2}} = icmp eq i64 {{jitx2}}, 111
//       br i1 %{{condx2}}, label %{{succbbx2}}, label %{{failbbx2}}
//
//     {{failbbx2}}:...
//       ...
//       %{{deoptx2}} = call ptr (...) @llvm.experimental.deoptimize...
//       ret ...
//
//     {{succbbx2}}:...
//       ...
//       %{{condz2}} = icmp eq i64 {{jitz2}}, 89
//       br i1 %{{condz2}}, label %{{succbbz2}}, label %{{failbbz2}}
//
//     {{failbbz2}}:...
//       ...
//       %{{deoptz2}} = call ptr (...) @llvm.experimental.deoptimize...
//       ret ...
//
//     {{succbbz2}}:...
//       ...
//       %{{res2}} = add {{size_t}} %{{arg2}}, 201...
//       ...
//     }
//     ...
//     --- End jit-post-opt ---
//     y=402
//     jit-state: enter-jit-code
//     y=603
//     y=804
//     y=1005
//     jit-state: deoptimise
//     jit-state: exit-jit-code

// Check that many-variable, many-function  promotion works in traces.

#include <assert.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <yk.h>
#include <yk_testing.h>

__attribute__((yk_promote("x", "z"))) uint64_t inner1(uint64_t x, uint64_t y,
                                                      uint64_t z) {
  y += x + z;
  return y;
}

__attribute__((yk_promote("x", "z"))) uint64_t inner2(uint64_t x, uint64_t y,
                                                      uint64_t z) {
  y += x / z;
  return y;
}

int main(int argc, char **argv) {
  YkMT *mt = yk_mt_new(NULL);
  yk_mt_hot_threshold_set(mt, 0);
  YkLocation loc = yk_location_new();

  uint64_t x = 111;
  uint64_t y = 0;
  uint64_t z = 89;
  NOOPT_VAL(x);
  NOOPT_VAL(z);

  for (int i = 0; i < 5; i++) {
    yk_mt_control_point(mt, &loc);
    y = inner1(x, y, z);
    y = inner2(x, y, z);
    fprintf(stderr, "y=%" PRIu64 "\n", y);
  }

  NOOPT_VAL(y);
  yk_location_drop(loc);
  yk_mt_drop(mt);
  return (EXIT_SUCCESS);
}
