[package]
name = "perftracer"
version = "0.1.0"
authors = ["The Yk Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
libc = "0.2.80"
strum = { version = "0.24.1", features = ["derive", "strum_macros"] }
strum_macros = "0.24.3"
deku = "0.16"
ykutil = { path = "../ykutil" }
intervaltree = "0.2.7"
byteorder = "1.4.3"
leb128 = "0.2.5"

[target.'cfg(target_arch = "x86_64")'.dependencies]
iced-x86 = { version = "1.18.0", features = ["decoder"]}

[build-dependencies]
cc = "1.0.62"
rerun_except = "1"
ykbuild = { path = "../ykbuild" }

[features]
yk_testing = []
